manifest:
  version: 0.13

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      path: zephyr
    - name: zmk
      remote: zmkfirmware
      revision: main
      path: zmk

  self:
    path: .
